target_repo: ghcr.io/bradfordwagner/go-builder
push_enabled: false

go_versions:
  - "1.26"
  - "1.27"

upstream:
  image: ghcr.io/bradfordwagner/ansible
  tag: 6.6.0

runtime:
  image: ghcr.io/bradfordwagner/base
  tag: 4.7.1

builds:
  - os: ubuntu_noble
    archs:
      - linux/amd64
      - linux/arm64
  - os: debian_trixie-slim
    archs:
      - linux/amd64
      - linux/arm64
