---
- hosts: localhost
  vars:
    go_ver: 1.18.3
    go_dev_install:
      - pkg: github.com/spf13/cobra-cli@latest
        target: cobra
#     - pkg: github.com/goreleaser/goreleaser@v1.9.2
#       target: goreleaser
  roles:
    - role: andrewrothstein.go-dev
