apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: go-builder-image-
spec:
  podGC:
    strategy: OnPodSuccess # delete pods when workflow is successful
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
      value: feature/arm
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
      - name: repo_name
        value: quay.io/bradfordwagner/go-builder
      - name: upstream_repo
        value: quay.io/bradfordwagner/ansible
      - name: upstream_tag
        value: 3.4.1
    dag:
      tasks:
      - name: ansible
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-go-builder.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: tag_suffix
            value: "-{{ item.platform }}"
          - name: platform
            value: "{{ item.platform }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
        templateRef:
          name: flavor-ansible-template
          template: "{{inputs.parameters.git_ref_type}}"
        withItems:
        - { p#atform: alpine_3.16    , runtime_platforms: [linux/arm64] }
#       - { platform: alpine_3.16    , runtime_platforms: [linux/amd64, linux/arm64] }

#       - { platform: debian_bullseye, runtime_platforms: [linux/amd64, linux/arm64] }
#       - { platform: debian_bookworm, runtime_platforms: [linux/amd64, linux/arm64] }
#       - { platform: alpine_3.15    , runtime_platforms: [linux/amd64, linux/arm64] }
#       - { platform: alpine_3.16    , runtime_platforms: [linux/amd64, linux/arm64] }
#       - { platform: ubuntu_focal   , runtime_platforms: [linux/amd64, linux/arm64] }
#       - { platform: ubuntu_kinetic , runtime_platforms: [linux/amd64, linux/arm64] }
