apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: go-builder-image-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: git_ref_type
      value: branches
    - name: git_version
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_ref_type
      - name: git_version
      - name: repo_name
        value: quay.io/bradfordwagner/go-builder
      - name: upstream_repo
        value: quay.io/bradfordwagner/ansible
      - name: upstream_tag
        value: 1.4.0
    dag:
      tasks:
      - name: ansible
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-go-builder.git
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: platform
            value: "{{ item.platform }}"
        templateRef:
          name: flavor-ansible-template
          template: "{{inputs.parameters.git_ref_type}}"
        withItems:
        - { platform: alpine_3.13     }
        - { platform: alpine_3.14     }
        - { platform: ubuntu_bionic   }
        - { platform: ubuntu_focal    }
        - { platform: debian_buster   }
        - { platform: debian_bullseye }

